### ISSUE TITLE
Beta test-Display of locking threshold in manually entered box truncated when running dApp on mobile.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#102]
1/11/22 Frontend v0.4.1-beta When voting, display of locking threshold value in manually entered box truncated when running on dApp on mobile.
![image](https://user-images.githubusercontent.com/77765830/199146017-907dc09f-046b-4c3d-9af8-a17216e7375d.png)

**Comment by sjmcpherson** [comment]
Fixed in v0.5.4

**Comment by judytan21** [comment]
21/11/22 Retest v0.5.7-beta. When voting using mobile, display of locking threshold value in manually entered box is now showing correctly. Fixed.
<img width="350" alt="image" src="https://user-images.githubusercontent.com/77765830/202942242-ee7c57bf-e1fe-4566-b373-54f01f329635.png">
