### ISSUE TITLE
Beta Test: Amount to mint was not cleared when changing the mint from balance. 

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#103]
2/11/22 Frontend v0.4.1-Beta. Account: tommccann. 
Scenario: When changing the mint from balance drop down box from POINTS to BEEBI,
max amount was not cleared and message "You do not have enough to complete the transaction" was displayed. 
Steps:
1) Choose a balance to Mint from: POINTS
2) Amount to Mint: Click Max. Populated with 57574 (max POINTS Balance). Correct.
3) Return to Choose a balance to Mint from: BEEBI (changing from POINTS to BEEBI).
4) Amount to Mint: Still showing 57574 which is the max POINTS balance and message "You do not have enough to complete the transaction" displayed. 
Expecting the Amount to mint to be cleared when changing from POINTS to BEEBI.
5) Click Max and Amount to Mint: 52.8666 (max BEEBI balance) displayed. Correct.

![image](https://user-images.githubusercontent.com/77765830/199373616-4752cff6-f63a-4211-bf9b-c44e43cb2e92.png)

![image](https://user-images.githubusercontent.com/77765830/199373560-46e89b60-cec4-42c4-8866-693c32ebcb81.png)

**Comment by stuartmcphersonflipmind** [comment]
Fixed in v0.5.3

**Comment by judytan21** [comment]
21/11/22 Frontend v0.5.7-beta. Retest. Amount field cleared when changing the mint from balance drop down box from POINTS to BEEBI. Fixed.
<img width="524" alt="Screen Shot 2022-11-21 at 1 11 45 PM" src="https://user-images.githubusercontent.com/77765830/202934457-539f4508-38d2-4f43-aec9-0bb5f43aef70.png">
<img width="524" alt="Screen Shot 2022-11-21 at 1 11 57 PM" src="https://user-images.githubusercontent.com/77765830/202934485-342bb20c-f486-42e3-98ee-5e9ce772f1c1.png">
