### ISSUE TITLE
When user has insufficient balance to pay mint fee, expected balance of mint currency displays as negative

### ISSUE THREAD

**Issue by tommccann777** [FreeosDAO/freeosgov_frontend#106]
The warning message is good, but in such an event it would be better if the expected balances either (a) don't display, or (b) remain at the current balance amounts.

![image](https://user-images.githubusercontent.com/18106735/202041215-1e16b8f4-6a78-4f93-96b9-a5ed04dfd09e.png)

**Comment by stuartmcphersonflipmind** [comment]
Expected balances hidden if balance error in v0.5.5

**Comment by judytan21** [comment]
21/11/22 Frontend v0.5.7-beta. Retest paying mint fee by foobar. tommccann's foobar bal=6036.095085 FOOBAR which is less than the required mint fee of 26166.787 FOOBAR. Expected FOOBAR balance is now hidden. Fixed.
_**Note: Unable to test with payment of mint fee by ZEPI (XPR) and BETA (FREEOS) as tommccann has sufficient ZEPI and BETA to pay  mint fee when minting the maximum POINTs. Unable to reduce or transfer ZEPI/BETA to another user as beta test env does not allow transferring of ZEPI or BETA.**_

<img width="524" alt="Screen Shot 2022-11-21 at 12 30 13 PM" src="https://user-images.githubusercontent.com/77765830/202932795-4ada3829-c5c6-4adc-a69f-d7f58228dc1c.png">

**Comment by judytan21** [comment]
Continue test...
1) SVR and claimed to Increase tommccann's POINT balance. Test paying mint fee with BETA. tommccan has insufficient BETA (12775.3809 BETA) to pay for mint fee of (17422.1427 BETA). Expected BETA balance is now hidden.
**_Note: Unable to test with payment of mint fee by ZEPI (XPR) as tommccann has sufficient ZEPI to pay mint fee when minting the maximum POINTs. Unable to reduce or transfer ZEPI to another user as beta test env does not allow transferring of ZEPI._**
<img width="902" alt="image" src="https://user-images.githubusercontent.com/77765830/202959007-b04866fd-b397-4c13-b8fe-f24e7c0d053f.png">
