### ISSUE TITLE
Launch-Locking threshold slider showing 'NaN'.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#108]
21/11/22 Frontend v0.5.7-beta. When entering a locking threshold value of 0.081 (out of range), the 1 was incorrectly entered as an 'i' instead of '1', resulting in an 'NaN' being displayed on the max end of the slider.
<img width="350" alt="image" src="https://user-images.githubusercontent.com/77765830/202942946-753ef8d5-ab0c-484a-b5ab-bb99d8c98634.png">

**Comment by judytan21** [comment]
22/11/22 Frontend v0.5.8-beta. Another example.
![Freeos Governance dApp 22-11-2022 11-21-36](https://user-images.githubusercontent.com/77765830/203170247-f8e54e06-0ebc-4075-ad7b-6c2ec5e80e97.png)

**Comment by stuartmcphersonflipmind** [comment]
Updated in v0.6.0, applied this to all the Voting inputs, so it handles decimal places & numbers but you cant paste other characters

**Comment by judytan21** [comment]
6/12/22 Unable to enter any decimal place in manually entered amount box i.e 0.03456 showing as 003456 which then becomes an out of range value.
![image](https://user-images.githubusercontent.com/77765830/205765888-6fa020b1-7744-49c2-ae14-0c2611390f47.png)

**Comment by judytan21** [comment]
6/12/22 Frontend v0.6.1 Was able to enter decimal places in manually entered amount box i.e 0.03456 accepted. Does not accept alphabetic chrs. Fixed.
![image](https://user-images.githubusercontent.com/77765830/205776818-d8f338f3-981c-4bd5-aa28-b7339db423d2.png)
![image](https://user-images.githubusercontent.com/77765830/205776952-8326f2ba-795f-41f1-af90-9cf44cf671d1.png)

![image](https://user-images.githubusercontent.com/77765830/205776882-d04b44b2-c717-4d35-b443-f2e59b100e5d.png)


![image](https://user-images.githubusercontent.com/77765830/205776182-cb453559-90b8-4404-a249-b6a5a8c7f704.png)
