### ISSUE TITLE
Wordings for Locking Threshold question is incorrect. Also "Almost done...." line missing.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#11]
20/7/22 freeosgov2 Frontend v0.1.5 verovera
Wordings for Vote Locking Threshold question is incorrect. Appears to be the same wordings as the Mint fee question. See screenshot below for correct wordings.
Also, next sentence "Almost done - Just check and submit your Vote" line missing.

Dave's UX:
<img width="436" alt="Screen Shot 2022-07-20 at 4 35 33 PM" src="https://user-images.githubusercontent.com/77765830/179898474-a9cd3211-80d2-4d23-b566-33d61e5e0eba.png">
freeosgov2 frontend: 
<img width="436" alt="Screen Shot 2022-07-20 at 4 36 33 PM" src="https://user-images.githubusercontent.com/77765830/179898493-61ccff0c-4273-427a-9695-b3bbeaf3b6bd.png">
.

**Comment by judytan21** [comment]
26/7/22 Retest. freeosgov2 frontend v0.1.6. Still showing incorrect wordings for Vote Locking Threshold question. Appears to be the same wordings as the Mint fee question. See screenshot below for correct wordings.
Also, next sentence "Almost done - Just check and submit your Vote" line missing.
Not fixed
![Freeos App 26-07-2022 14-38-08](https://user-images.githubusercontent.com/77765830/180911406-be31ae05-5cc4-469b-854d-4eee5e5a85c0.png)
.

**Comment by stuartmcphersonflipmind** [comment]
fixed in v1.12

**Comment by judytan21** [comment]
2/8/22 freeosgov2 frontend v0.1.13. Fixed.
<img width="528" alt="Screen Shot 2022-08-02 at 11 41 57 AM" src="https://user-images.githubusercontent.com/77765830/182263534-a267bf55-46b0-48b5-951f-49d5cbaae099.png">
