### ISSUE TITLE
Upward or downward pointing arrows missing from "This week's Vote Results"

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#12]
20/7/22 freeosgov2 v0.1.4 verovera 
Under "This week's Vote Results" section, the upward or downward pointing arrows indicating an increase/decrease in values are missing.   
Dave's UX:
<img width="436" alt="Screen Shot 2022-07-20 at 4 57 37 PM" src="https://user-images.githubusercontent.com/77765830/179900724-fa081c0b-f16c-4bee-9c62-13a91690ee04.png">

Freeosgov2 frontend:
<img width="436" alt="Screen Shot 2022-07-20 at 4 56 50 PM" src="https://user-images.githubusercontent.com/77765830/179900771-885296a7-fa4f-4422-8fe0-7756f5c2a55e.png">

**Comment by stuartmcphersonflipmind** [comment]
OK I will sort this

**Comment by stuartmcphersonflipmind** [comment]
This is done v1.13

**Comment by judytan21** [comment]
2/8/22 freeosgov2 frontend v0.1.13. Fixed
![Freeos App 02-08-2022 11-56-12](https://user-images.githubusercontent.com/77765830/182264341-82dbadc6-fdc4-4af2-b701-4c472bd7e1d0.png)
.
