### ISSUE TITLE
Minor wording change required on 'Yay you did it' page.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#17]
26/7/22 freeosgov2 frontend v0.1.6. account: verovera type 'v' registered.
After voting successfully, was presented with 'Yay you did it..' page.
Change "Thanks for participating in this week vote" to "Thanks for participating in this week's vote"

![Freeos App 26-07-2022 15-40-22](https://user-images.githubusercontent.com/77765830/180918096-b5c90789-3eff-41de-ab7d-5fb7f981fad9.png)

.

**Comment by stuartmcphersonflipmind** [comment]
fixed in v1.12

**Comment by judytan21** [comment]
2/8/22 freeosgov2 frontend v0.1.13. Wording corrected. Fixed.
<img width="528" alt="Screen Shot 2022-08-02 at 11 43 24 AM" src="https://user-images.githubusercontent.com/77765830/182263141-a0146d15-80f8-4f47-9e2e-cf8faba09eb8.png">
