### ISSUE TITLE
On Claims page, verify link is not taking participant to new wiki.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#19]
1/8/22 freeosgov2 frontend v0.1.10. account: alanappleton type 'd' unregistered.
On Claims page, clicking "How to verify your account? " link takes you to the "Staking and KYC Update" article instead of the new wiki: https://docs.freeos.io/d/h/6k0z3-408/43bbcca7c54387a/6k0z3-1502

**Comment by conorseed** [comment]
Fixed in v0.1.16

**Comment by judytan21** [comment]
3/8/22 Retest. freeosgov2 frontend v0.1.16 account: alanappleton
Link: https://twilight-cloud-0240.on.fleek.co/#/activities. Fixed.
![Using the Freeos dApp - KYC to Verify your Account 03-08-2022 16-06-36](https://user-images.githubusercontent.com/77765830/182521940-bcd4d382-b4c0-4413-9929-20d4246ddee3.png)
.
