### ISSUE TITLE
Survey slider control - month/s missing from minimum/maximum values. 

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#2]
13/7/22 Governance Frontend v0.1.1 Survey Completion.
1. Survey "Q2. Crypto Market Change of Direction" on the slider, 'months' missing from min and max values.
2. Survey "Q4: FREEOS Change of Direction" on the slider, 'months' missing from min and max values.
![Freeos App 13-07-2022 11-32-56](https://user-images.githubusercontent.com/77765830/178616455-fded55a8-10d0-4f69-8292-e14bb5ca49d3.png)
Dave's UX:
<img width="457" alt="Screen Shot 2022-07-13 at 11 45 08 AM" src="https://user-images.githubusercontent.com/77765830/178616779-19b6dd91-cd2f-49e1-86e8-03aac20de456.png">
<img width="443" alt="Screen Shot 2022-07-13 at 12 16 51 PM" src="https://user-images.githubusercontent.com/77765830/178622249-c83ac929-59c8-48e9-b626-c67be3ea1581.png">
.

**Comment by stuartmcphersonflipmind** [comment]
I think this will be left off for MVP

**Comment by conorseed** [comment]
Fixed in v0.1.16

**Comment by judytan21** [comment]
3/8/22 Retest. freeosgov2 frontend v0.1.16 account: verovera Link: https://twilight-cloud-0240.on.fleek.co/#/activities. Fixed.
![Freeos App 03-08-2022 16-13-37](https://user-images.githubusercontent.com/77765830/182522868-07e561fb-75c4-45ba-84be-ff9b24c64af1.png)
![Freeos App 03-08-2022 16-14-36](https://user-images.githubusercontent.com/77765830/182522882-bec17382-5ad3-4299-abc4-94838c01358a.png)
.
