### ISSUE TITLE
Wording changes required on Survey Results page.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#20]
1/8/22 freeosgov2 frontend v0.1.10 Survey Results page
Wording changes required:
1. "This Weeks Survey Results" to "This Week's Surver Results".
2. "Thank you to everyone.....This weeks survey results are:' to "Thank you to everyone.....This week's survey results are:".
3. "Q2: How long before the crypto market changes direction?:"- remove ":" at the end of sentence.
4. Button "Start this Weeks Vote" to "Start this Week's Vote".
![Freeos App 01-08-2022 12-20-58](https://user-images.githubusercontent.com/77765830/182075470-7c12e81b-2a87-4443-a6c6-ee42cc726948.png)
![Freeos App 01-08-2022 12-21-14](https://user-images.githubusercontent.com/77765830/182075629-3bbc5172-30e6-4aed-91de-4c270f0dfec4.png)

**Comment by stuartmcphersonflipmind** [comment]
Fixed in v1.12

**Comment by judytan21** [comment]
2/8/22 freeosgov2 frontend v0.1.13. Fixed

![Freeos App 02-08-2022 11-20-43](https://user-images.githubusercontent.com/77765830/182261560-7f7ef1d9-99e8-44e6-9cd1-17a10aff337c.png)
![Freeos App 02-08-2022 11-21-29](https://user-images.githubusercontent.com/77765830/182261703-758ae8f0-7759-45eb-9222-e594a9cce4a2.png)
