### ISSUE TITLE
Minor wording change required on "This week's Vote Results" page.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#21]
2/8/22 freeosgov2 frontend v0.1.13.
Change "Do you agree...this weeks VOTE...." to "Do you agree...this week's VOTE....".
![Freeos App 02-08-2022 11-56-12](https://user-images.githubusercontent.com/77765830/182264749-91e438fe-7ac9-4587-9fce-f53778749019.png)
'

**Comment by sjmcpherson** [comment]
Fixed in v1.15

**Comment by judytan21** [comment]
3/8/22 Retest. freeosgov2 frontend v0.1.16 account: verovera Link: https://twilight-cloud-0240.on.fleek.co/#/activities. Fixed
![Freeos App 03-08-2022 16-52-47](https://user-images.githubusercontent.com/77765830/182527172-cdf0547a-8e89-4825-b3b2-20e80eba8636.png)
.
