### ISSUE TITLE
On Claims page, unlock points link taking user to wrong section of wiki.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#22]
3/8/22 freeosgov2 frontend v0.1.16 account: verovera Link: https://twilight-cloud-0240.on.fleek.co/#/
On Claims page (Locked Points section), clicking "For more info on Locked Points [click here]" and was taken to "Locked Points" section of new Wiki. Correct.
However, clicking "Your Points cannot be unlocked. For more info [click here.]" and was also taken to "Locked Points" section of new Wiki. Expecting to be taken to the "Unlocking Points" section of the new Wiki.

**Comment by conorseed** [comment]
Fixed in v0.1.17

**Comment by judytan21** [comment]
8/8/22 freeosgov2 frontend v0.1.17. Fixed
![Using the Freeos dApp - Unlocking Points 08-08-2022 10-47-12](https://user-images.githubusercontent.com/77765830/183313967-cce0adcb-6030-4a75-a9eb-8f33c8a5c372.png)
.
