### ISSUE TITLE
On 'Converting Points to FREEBI' page, remove unwanted line of text.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#24]
8/8/22 freeosgov2 frontend v0.1.17 Mint FREEBI. 
On the 'Converting Points to FREEBI' page,  beneath the 'Amount to Convert', remove text 'from your "from account"'.
Ref Tom's reply to my question:
Tom | freeos.io | freedao.io — 8/8/22 Today at 15:14
@Jude That line shouldn't be there. It's either a mistake in the spec or in development. The from account is going to be whoever is logged in, so there's no need for that text
![Freeos App 08-08-2022 14-35-40](https://user-images.githubusercontent.com/77765830/183332848-002defb2-adb1-477c-8c8e-d11e2f9bbf65.png)
.

**Comment by stuartmcphersonflipmind** [comment]
Fixed in v0.1.25 now says the more useful
![image](https://user-images.githubusercontent.com/58194035/185244242-d86e7037-3274-4c76-97d5-3e7c2dc69aec.png)

**Comment by judytan21** [comment]
22/8/22 Retest. freeosgov2 frontend v0.2.1. Checked with Tom if he is happy with the change as he wanted the text line to be removed initially. Fixed.
Tom | freeos.io | freedao.io — Today at 10:56
I see what he has done. It looks ok to me
![Freeos Governance dApp 22-08-2022 11-01-01](https://user-images.githubusercontent.com/77765830/185814494-f6d78cd4-9e1c-4d6c-b3b2-d91611db1e4e.png)
