### ISSUE TITLE
Expected FREEBI balance incorrectly described as POINTS balance.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#25]
8/8/22 freeosgov2 frontend v0.1.17 Mint FREEBI.
On the 'Converting Points to FREEBI' page, in the section below: expected FREEBI balance incorrectly described as POINTS balance.
Expected conversion transaction balances will show here
POINTS balance will be: 0
POINTS balance will be: 10902.1934. Expecting "FREEBI balance will be: 10902.1934". 

![Freeos App 08-08-2022 14-52-57](https://user-images.githubusercontent.com/77765830/183333436-946878fc-07bb-42c2-bec5-db1d83aa0a93.png)
.

**Comment by stuartmcphersonflipmind** [comment]
Fixed in v0.1.25

**Comment by judytan21** [comment]
22/8/22 Retest. freeosgov2 frontend v0.2.1. Fixed
![Freeos Governance dApp 22-08-2022 11-08-06](https://user-images.githubusercontent.com/77765830/185814710-6f7ea2ff-155f-42ea-90d6-ef215749060c.png)
.
