### ISSUE TITLE
Expected POINTS/FREEBI balance to be displayed with 4 decimal places when a fractional amount entered.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#26]
8/8/22 freeosgov2 frontend v0.1.17 Mint FREEBI., verovera type 'v'
When converting fractional POINTs to FREEBI i.e. Amount to convert: 1.2345, the expected POINTS/FREEBI balances were shown with a long string of decimal places. Expecting POINTS/FREEBI balances to be shown up to 4 dec places like all the other amounts.
Expected conversion transaction balances will show here
POINTS balance will be: 10889.658099999999
POINTS balance will be:12.535300000000001

![Freeos App 08-08-2022 16-03-20](https://user-images.githubusercontent.com/77765830/183336688-58780177-e627-456c-a155-4fdf14f3edd6.png)

**Comment by stuartmcphersonflipmind** [comment]
Fixed in v0.1.25

**Comment by judytan21** [comment]
22/8/22 Retest. freeosgov2 frontend v0.2.1. Fixed.
![Freeos Governance dApp 22-08-2022 11-08-06](https://user-images.githubusercontent.com/77765830/185814804-32018588-a37b-4592-a383-67a12ed6ed3f.png)
