### ISSUE TITLE
Instances where the 'Convert to FREEBI' button was not enabled after entering amount.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#27]
8/8/22 freeosgov2 frontend v0.1.17 Mint FREEBI., verovera type 'v' POINTS bal: 10890.8926 FREEBI bal: 11.3008
When converting 5 POINTs to FREEBI, the 'Convert to FREEBI' button was not enabled after entering the amount.
Steps:
1. Connect wallet.
2. Login: verovera
3. Select 'Mint'. Amount to convert initially showing as 0.
4. Enter 5 POINTs and tab out.
5. Convert to FREEBI button was not enabled. Expecting button to be enabled.
6. Repeat tests several times. See examples where it did not work as expected. Seems to be intermittent.

![Freeos App 08-08-2022 16-43-26](https://user-images.githubusercontent.com/77765830/183340914-0fdcf434-c94b-444e-b9c1-a7a9edba5c3a.png)

![Freeos App 08-08-2022 16-34-14](https://user-images.githubusercontent.com/77765830/183340607-20e1504e-e8d4-4bf1-94a4-677c17df6b8f.png)

![Freeos App 08-08-2022 16-36-44](https://user-images.githubusercontent.com/77765830/183340622-8ba153ae-4f7c-4c0e-a06e-752e1d3ea202.png)

**Comment by judytan21** [comment]
9/8/22 freeosgov2 frontend v0.1.17
Hey Stuart, JeromeK is experiencing the same issue where the Convert to FREEBI button was not enabled. 
JeromeK's comments below:
Mint 
Points to FREEBI
Why is manually entering my amount not allowing the button to press, while pressing “Max” is fine
<img width="458" alt="Screen Shot 2022-08-09 at 1 15 31 PM" src="https://user-images.githubusercontent.com/77765830/183541540-f88f0720-2770-4346-95bf-2829baa3dabe.png">

**Comment by stuartmcphersonflipmind** [comment]
Fixed in v0.1.25

**Comment by judytan21** [comment]
22/8/22 Retest. freeosgov2 frontend v0.2.1. Convert button enabled for both manually entered and Max amount. Fixed. 
![Freeos Governance dApp 22-08-2022 11-16-14](https://user-images.githubusercontent.com/77765830/185815062-bbbbba4a-af03-43fa-95c0-3c64489b2da7.png)
![Freeos Governance dApp 22-08-2022 11-16-30](https://user-images.githubusercontent.com/77765830/185815069-a4f540da-b0f5-4aa4-b226-52dbe9f02126.png)
