### ISSUE TITLE
Rename menu item for Claim page.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#28]
8/8/22 freeosgov2 frontend v0.1.18 
Menu item for Claim page does not match Dave's UX. Should be 'Claim / Assets'.
Dave's UX. 
![Flow 1 09-08-2022 12-52-22](https://user-images.githubusercontent.com/77765830/183539657-12350638-3a0a-4111-8e7c-bcbcbc1861c9.png)
.

**Comment by conorseed** [comment]
v0.1.19 should fix this!

**Comment by judytan21** [comment]
10/8/22 Retest. freeosgov2 frontend v0.1.19. Fixed
![Freeos Governance dApp 10-08-2022 11-09-17](https://user-images.githubusercontent.com/77765830/183777698-0a5983a3-3c3a-4947-a370-16e5d5095184.png)
.
