### ISSUE TITLE
Unable to register verified user.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#29]
9/8/22 freeosgov2 frontend v0.1.18 account: darlenedole 'v'. Not registered. No participant record.
Steps
1. Connect wallet and login as darlenedole.
2. Prompted to register. Correct.
3. Tick acceptance of Terms of Service.
4. Register button enabled. Correct.
5. Click Register. Nothing happens.
6. User not registered. Participant record not created.

![Freeos App 09-08-2022 13-39-00](https://user-images.githubusercontent.com/77765830/183544235-77b44bf6-b4e9-460d-ad3c-68f6f3b36d3f.png)
![Freeos App 09-08-2022 13-39-14](https://user-images.githubusercontent.com/77765830/183544242-7cd85d38-ad22-43f2-b760-295fdd0a84a9.png)

**Comment by stuartmcphersonflipmind** [comment]
Fixed in v0.1.26

**Comment by judytan21** [comment]
22/8/22 Retest. freeosgov2 frontend v0.2.1. vincentvegan 'v' unregistered was registered successfully in iteration 461424. Participant record created. Fixed.
![Freeos Governance dApp 22-08-2022 11-32-11](https://user-images.githubusercontent.com/77765830/185815726-40c94a14-9a66-4aca-9281-7ca983a37ef1.png)
![Freeos Governance dApp 22-08-2022 11-32-40](https://user-images.githubusercontent.com/77765830/185815730-0ba49fb1-06cd-4a80-8db7-f504bcacf295.png)
![Freeos Governance dApp 22-08-2022 11-33-13](https://user-images.githubusercontent.com/77765830/185815746-28de7bab-6e5f-4040-a0f4-461894de3a94.png)
![Account - Proton Testnet 22-08-2022 11-33-55](https://user-images.githubusercontent.com/77765830/185815756-a6ff9e5d-fbc5-4ae9-88f6-083d36d65232.png)
