### ISSUE TITLE
Unable to send tokens.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#30]
9/8/22 freeosgov2 frontend v0.1.18 account: verovera 'v'. 
Unable to send tokens. Not sure if this function has been completed.

Steps
1. Connect wallet and login as verovera.
2. On Send Tokens, message 'You have nothing in your account to transfer currently' displayed even though user has tokens available for sending.
![Freeos App 09-08-2022 14-30-07](https://user-images.githubusercontent.com/77765830/183550590-efe1c15c-e369-4c41-a5a7-7ccbc2bd76f5.png)
![Freeos App 09-08-2022 14-29-28](https://user-images.githubusercontent.com/77765830/183550610-df875dd5-dfc5-41bd-bab0-40e706293a4e.png)

JeromeK is experiencing the same issue. See comments below:
Send Tokens
It says that there is nothing in my account to transfer currency (I was hoping to test the FREEBI transfer from a registered account to a non-registered account)
However, I have 10 FREEOS and 50 FREEBI.  Is this not done yet?

**Comment by conorseed** [comment]
@judytan21 - this hasn't been done yet. Need Tom to write a spec!

**Comment by judytan21** [comment]
16/8/22 Retest. freeosgov2 frontend v0.1.22. Able to send FREEOS/FREEBI tokens. Fixed.
