### ISSUE TITLE
Ability to resize font dynamically to handle large numbers and decimals.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#31]
9/8/22 freeosgov2 frontend v0.1.18 
From JeromeK. 
Display of Currencies
We need to handle large numbers + decimals better.  Can the font resize dynamically (I’d make it universal so all instances change at the same time to keep the display consistent)

<img width="440" alt="Screen Shot 2022-08-09 at 3 01 42 PM" src="https://user-images.githubusercontent.com/77765830/183554372-c5e37544-e7e2-4bf8-9df8-5e8d226b4743.png">

**Comment by conorseed** [comment]
Hey @judytan21 - apologies for accidentally closing this! 

**Fixed in v0.1.20**

Talked with Tom, Stuart & Jerome about this - we decided the best solution was an abbreviation of numbers instead of font sizes. 

So, numbers under 1000 go to 2 decimal points, numbers in the thousands are abbreviated to have "K" at the end, millions "M", billions, "B".
e.g. 1200.2548 is abbreviated to 1.2K. 

There's also an added tooltip after each balance, which will show the unabbreviated value when hovered over. 

See screenshot as an example:
![Screen Shot 2022-08-11 at 11 45 40 AM](https://user-images.githubusercontent.com/13262289/184042412-76d3553d-e28e-43ec-8b35-30339b7af1a7.png)

**Comment by judytan21** [comment]
15/8/22 Retest. freeosgov2 frontend v0.1.21. 
1) Millions - alanappleton->Point bal=2,012,345.6789 POINT. Lock bal=2,012,345.6789 POINT.
On Claims page, both abbreviated balances showing correctly. Fixed. 

2) Billions - alanappleton -> Point bal=2777012345.6789 POINT   Lock bal=2777012345.6789 POINT
On Claims page, both abbreviated balances showing correctly. Fixed.
**Note:** _unable to test Millions for FREEBI and FREEOS balances are showing correctly as do not have the tool to populate test account with these huge balances without involving the developers._
Millions:
<img width="459" alt="Screen Shot 2022-08-15 at 1 46 48 PM" src="https://user-images.githubusercontent.com/77765830/184565162-25144c86-99b5-456c-b013-a680517f6cf5.png">
<img width="459" alt="Screen Shot 2022-08-15 at 1 46 59 PM" src="https://user-images.githubusercontent.com/77765830/184565170-cd1a405f-0b88-46bc-851e-543d31131ab0.png">
Billions:
<img width="459" alt="Screen Shot 2022-08-15 at 1 58 59 PM" src="https://user-images.githubusercontent.com/77765830/184565677-fd089ae9-6951-4e1d-922b-d70d37906cb8.png">
<img width="459" alt="Screen Shot 2022-08-15 at 1 59 09 PM" src="https://user-images.githubusercontent.com/77765830/184565687-7b554d40-1e75-40ea-8ea8-9cbeb2dfa011.png">

**Comment by judytan21** [comment]
@conorseed Hey...is there a quick way to push miliions/billions into FREEBI/FREEOS balance so i could check its displaying correctly.

**Comment by conorseed** [comment]
@judytan21 Millions testing on local machine:
![Screen Shot 2022-08-15 at 2 57 53 PM](https://user-images.githubusercontent.com/13262289/184569933-2ca8dd40-f40d-422a-88fa-4a34349d5706.png)
![Screen Shot 2022-08-15 at 2 58 04 PM](https://user-images.githubusercontent.com/13262289/184569940-615d63b4-6eb3-41c4-88d1-7544f1fea0fc.png)

Billions testing:
![Screen Shot 2022-08-15 at 2 58 36 PM](https://user-images.githubusercontent.com/13262289/184570021-a1f48146-1253-414c-8fa0-0b6f3d0629e4.png)
![Screen Shot 2022-08-15 at 2 58 29 PM](https://user-images.githubusercontent.com/13262289/184570029-32ac7b12-6021-47c3-97dc-1cb8d31614ad.png)

**Comment by judytan21** [comment]
15/8/22 Awesome team collaboration Conor. Thanks so much. Fixed.
