### ISSUE TITLE
Minor wording change for Vote page

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#33]
10/8/22 freeosgov2 frontend v0.1.19 
Change wording "Last weeks Issuance: 0.5%" to "Last week's Issuance: 0.5%". missing apostrophe.
![Freeos Governance dApp 10-08-2022 11-34-45](https://user-images.githubusercontent.com/77765830/183781935-42c776d7-aadd-4d01-bc83-f56dea4be6fb.png)

**Comment by conorseed** [comment]
Fixed in v0.1.20

**Comment by judytan21** [comment]
15/8/22 Retest. freeosgov2 frontend v0.1.21. Fixed.
![Freeos Governance dApp 15-08-2022 11-22-41](https://user-images.githubusercontent.com/77765830/184558768-d739077a-7474-4615-8055-9cfae6a6cd6c.png)
