### ISSUE TITLE
Unlocked amount shown on Woohoo pop up was truncated when unlocking a huge number of POINTs.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#41]
23/8/22 freeosgov2 frontend v0.2.2 jamiejackson 'v' registered with Locked POINTs bal: 1733133404.6789 POINT
When unlocking 21% of user's Locked balance,  of 363958015 POINTs were unlocked. However, the unlocked amount shown on the Woohoo pop up was truncated.

<img width="582" alt="Screen Shot 2022-08-23 at 12 49 37 PM" src="https://user-images.githubusercontent.com/77765830/186044729-1d2cae86-22cd-4822-92e6-b72e26ca924a.png">

**Comment by stuartmcphersonflipmind** [comment]
Value Abbreviation Component added to fix this in v0.2.3

**Comment by judytan21** [comment]
24/8/22 freeosgov2 frontend v0.2.3 jamiejackson 'v' registered with Locked POINTs bal: 1369175389.6789 POINT.
When unlocking 15% of user's Locked balance (failsafe) in iteration 461476,  205376309 POINTs were unlocked. 
Unlocked amount shown on the Woohoo pop up showing as 205M. Correct. Fixed.

<img width="475" alt="Screen Shot 2022-08-24 at 3 34 01 PM" src="https://user-images.githubusercontent.com/77765830/186324328-85996729-e486-49b9-8105-4ae908194fbf.png">
<img width="475" alt="Screen Shot 2022-08-24 at 3 34 58 PM" src="https://user-images.githubusercontent.com/77765830/186324467-5b7d342f-330a-4e14-b47a-5cbfde27614e.png">
