### ISSUE TITLE
Verified, unregistered user was able to access the Mint page.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#43]
24/8/22 freeosgov2 frontend v0.2.3 backend v0.9.43
User deliadally 'v' verified but not registered was able to access the Mint page. Expecting Mint menu item to be unavailable for verified, unregistered users as per Tom's specs below:
Tom's specs:
"The menu item for Mint and the Mint page are only available for all registered and verified users (where [userRecord].account_type == "v" or "b" or "c")".
![Freeos Governance dApp 24-08-2022 11-45-50](https://user-images.githubusercontent.com/77765830/186285852-452bc10c-76eb-4e1d-a4fa-f52fd5b5290f.png)

**Comment by stuartmcphersonflipmind** [comment]
Fixed in v0.2.4

**Comment by judytan21** [comment]
29/8/22 Retest freeosgov2 frontend v0.2.4 backend v0.9.44 Iteration=461593, deliadally, v, verified unregistered user.
Mint menu item is now unavailable. Fixed.
![Freeos Governance dApp 29-08-2022 12-19-36](https://user-images.githubusercontent.com/77765830/187101123-5f6a3b7f-6248-4944-88e5-ea219ba0b5d0.png)
