### ISSUE TITLE
Minor text change on Mint FREEOS tab.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#44]
24/8/22 freeosgov2 frontend v0.2.3 backend v0.9.43
On Mint Page (Mint FREEOS) tab, line "More info click here", underline "click here" and change text colour to be consistent with Mint FREEBI tab
![Freeos Governance dApp 24-08-2022 12-09-20](https://user-images.githubusercontent.com/77765830/186287568-72466696-e03a-4bee-9ffd-95953cd7a0e0.png)
![Freeos Governance dApp 24-08-2022 12-09-33](https://user-images.githubusercontent.com/77765830/186287578-c40eb623-484c-4f61-a9f0-97a3aaabe49e.png)
.

**Comment by stuartmcphersonflipmind** [comment]
Fixed in in v0.2.4

**Comment by judytan21** [comment]
29/8/22 Retest freeosgov2 frontend v0.2.4 backend v0.9.44 Iteration=461593 Fixed
![Freeos Governance dApp 29-08-2022 12-26-20](https://user-images.githubusercontent.com/77765830/187101517-dc41a59c-0e45-4ec4-9889-e3fee0649dee.png)
.
