### ISSUE TITLE
On Mint Page (Mint FREEOS) tab, 'More Info' link unavailable for selection.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#45]
24/8/22 freeosgov2 frontend v0.2.3 backend v0.9.43
On Mint Page (Mint FREEOS) tab, 'More Info' link unavailable for selection.
![Freeos Governance dApp 24-08-2022 12-09-20](https://user-images.githubusercontent.com/77765830/186288039-441b02eb-439c-405f-8703-ec644d42bc8f.png)

**Comment by stuartmcphersonflipmind** [comment]
Fixed in in v0.2.4

**Comment by judytan21** [comment]
29/8/22 Retest freeosgov2 frontend v0.2.4 backend v0.9.44. On Mint Page (Mint FREEOS) tab, 'More Info' link is now available for selection. Fixed.
