### ISSUE TITLE
Mint free points section displayed for users without any mint free points.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#46]
24/8/22 freeosgov2 frontend v0.2.3 backend v0.9.43 vincentvegan 'v' registered, No Mint free Points.
On Mint Page (Mint FREEOS) tab, the 'Mint Free Points balance' section was displayed where mffbalance = 0. Expecting it to be hidden as per Tom's specs below:
Tom's spec:
3. Mint Free Points balance
Display this section only if [mffBalance] > 0 POINT
Display [mffBalance]

![Freeos Governance dApp 24-08-2022 13-56-06](https://user-images.githubusercontent.com/77765830/186300592-dfc1b5af-3e12-41ac-93a0-d01554015e6d.png)
![Account - Proton Testnet 24-08-2022 13-59-03](https://user-images.githubusercontent.com/77765830/186300974-7b80c37d-ded9-4647-a7c5-f7e287885fc5.png)

**Comment by stuartmcphersonflipmind** [comment]
Removed References to MFF in v0.2.4 if balance 0

**Comment by judytan21** [comment]
29/8/22 Retest freeosgov2 frontend v0.2.4 backend v0.9.44. On Mint Page (Mint FREEOS) tab, the 'Mint Free Points balance' section is now hidden when mffbalance = 0. Fixed
![Freeos Governance dApp 29-08-2022 13-58-13](https://user-images.githubusercontent.com/77765830/187108625-d2432999-d1ae-4b21-8eff-f876a0701615.png)

![Freeos Governance dApp 29-08-2022 14-00-15](https://user-images.githubusercontent.com/77765830/187108699-4fef0ff6-2028-4b73-a5bb-c9c67dcfcbf3.png)

.
