### ISSUE TITLE
Show user's account when displaying the 'from account' line. 

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#47]
24/8/22 freeosgov2 frontend v0.2.3 backend v0.9.43 verovera 'v' registered
On Mint Page (Mint FREEOS) tab, 'Create a MINT Transaction' section, underneath '2. Amount to Mint:', 
change text "from your ‘from account’" to :"from account 'verovera'" as shown on the 'POINTs to FREEBI' tab.
Mint FREEOS tab
<img width="475" alt="Screen Shot 2022-08-24 at 2 44 44 PM" src="https://user-images.githubusercontent.com/77765830/186309782-f77b9ea0-9721-415e-bb2a-22b7bfcc7a00.png">
POINTs to FREEBI tab
<img width="475" alt="Screen Shot 2022-08-24 at 2 45 12 PM" src="https://user-images.githubusercontent.com/77765830/186309799-9ea4f206-c051-4a22-8d55-3ce8698c6d9d.png">
.

**Comment by stuartmcphersonflipmind** [comment]
Fixed in v0.2.4

**Comment by judytan21** [comment]
29/8/22 Retest freeosgov2 frontend v0.2.4 backend v0.9.44. On Mint Page (Mint FREEOS) tab, 'Create a MINT Transaction' section, underneath '2. Amount to Mint:', text "from account 'verovera'" is now showing the user's account to be consistent with 'POINTs to FREEBI' tab. Fixed.
![Freeos Governance dApp 29-08-2022 14-08-27](https://user-images.githubusercontent.com/77765830/187109122-805287d7-7521-4ea6-8bae-48ee7236b35e.png)
