### ISSUE TITLE
Pending request message displayed when voting mint fee as fractions.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#50]
30/8/22 freeosgov2 frontend v0.2.6 backend v0.9.45 iter 461621
verovera voted FREEOS Mint fee=10.1234, XPR mint fee=20.5678 and XUSDC mint fee=30, a "Pending request" message was displayed and was unable to submit vote.
Discussed this with Tom and he has recommended the following resolution: 
Tom | freeos.io | freedao.io — 30/8/22 Today at 16:49
The best way is for the slider to not allow floating point numbers, to make sure that integers are selected only. The second-best way is for Stuart to convert what the user selected to an integer, e.g. convert 8.6 to 9
Either way, the backend expects an integer.
![Freeos Governance dApp 30-08-2022 16-29-33](https://user-images.githubusercontent.com/77765830/187354231-96b69f09-6e02-43a9-bd7b-0ce955c12b13.png)
![Freeos Governance dApp 30-08-2022 16-26-09](https://user-images.githubusercontent.com/77765830/187354287-a92381d0-c5d3-437e-aec5-7e235bb38985.png)
![Freeos Governance dApp 30-08-2022 16-26-22](https://user-images.githubusercontent.com/77765830/187354672-fe1e37b3-20a9-4dc3-a025-8fd9df46ceaf.png)
![Freeos Governance dApp 30-08-2022 16-26-36](https://user-images.githubusercontent.com/77765830/187354733-597eb826-08d0-481a-a283-9a77018e7579.png)

**Comment by stuartmcphersonflipmind** [comment]
Fixed in v0.2.5 Can't input a decimal now

**Comment by judytan21** [comment]
31/8/22 Retest. freeosgov2 frontend v0.2.6ii backend v0.9.47 iter 461641, 
verovera and vivvestin both voted successfully. Not seeing the 'pending request' message anymore.
Unable to enter values with decimals, only integers allowed. Fixed.
