### ISSUE TITLE
On Vote page, last week's issuance rate was displayed incorrectly.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#51]
30/8/22 freeosgov2 frontend v0.2.6 backend v0.9.45 iter 461621
In iteration 461621, verovera voted Issuance rate= 75%. 
In the next iteration 461622, on the Vote page, Last week's issuance rate was showing as 0.75%. Expecting to show as 75%.

![Freeos Governance dApp 30-08-2022 17-22-37](https://user-images.githubusercontent.com/77765830/187356395-66ab19c5-c31d-42af-86ad-812a9f7499b7.png)

**Comment by stuartmcphersonflipmind** [comment]
Fixed in v0.2.6 Issuance Rate displayed correctly

**Comment by judytan21** [comment]
31/8/22 Retest. freeosgov2 frontend v0.2.6ii backend v0.9.47 iter 461641
In iteration 461641, verovera voted Issuance rate= 75% and vivvestin voted issuance rate=100%.
When Ratifying vote, this week's voted values showing correctly.
In the next iteration 461642, on the Vote page, Last week's issuance rate was showing as 87.5%. Correct.

![Freeos Governance dApp 31-08-2022 12-52-29](https://user-images.githubusercontent.com/77765830/187569567-6f5d4e64-a976-404f-bf8c-f2ae2b6d08f0.png)
![Freeos Governance dApp 31-08-2022 13-39-49](https://user-images.githubusercontent.com/77765830/187573982-31c3fca6-ea11-40cf-b9b6-e28a63adfdc7.png)
