### ISSUE TITLE
Current Locking threshold on the Vote page is not showing the voted average locking threshold.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#53]
31/8/22 freeosgov2 frontend v0.2.6ii backend v0.9.48 
Current Locking Threshold value on the Vote page is different from the Current Locking Threshold value on the Ratify page. 
On Vote page, current locking threshold is showing as 0.0167 whilst the value on Ratify page is 0.022525.
Expecting both to be displaying the average voted locking threshold value of 0.022525.

Locking Threshold on the Vote page was taken from the exchange rate table whilst the Locking Threshold on the Ratify page is taken from Rewards table. Refer Tom's specs.
Tom has now updated frontend Ratify specs to take the Locking Threshold value from exchange rate table. 
Stuart to make the change to the frontend Ratify page and Tom to change backend code so the exchange rate table is updated with the average voted locking threshold value.
Ratify page:
![image](https://user-images.githubusercontent.com/77765830/187591893-0bc448c8-17c1-4399-bfea-394083f4a335.png)
Vote Page:
![image](https://user-images.githubusercontent.com/77765830/187591980-f55d52a2-e11b-47c6-bc61-4e4690bf3505.png)

**Comment by stuartmcphersonflipmind** [comment]
Current Locking Threshold value changed in v0.2.7

**Comment by judytan21** [comment]
5/9/22 Retest. freeosgov2 frontend v0.2.12 backend v0.9.51
Current locking threshold on Vote and Ratify page now showing the average voted threshold value of 0.02835000000000000.  Exchange rate table was also updated with the average voted locking threshold value. Fixed.
Ratify page
![Freeos Governance dApp 05-09-2022 11-53-48](https://user-images.githubusercontent.com/77765830/188338823-e6cd6b74-5c74-4ad0-98a2-e650bb4ca803.png)
Vote page
![Freeos Governance dApp 05-09-2022 12-22-45](https://user-images.githubusercontent.com/77765830/188339446-098b0901-c84a-4b01-b39f-6223e980f5e2.png)
Rewards record
![freeosgov2 - XPR Account - Proton Testnet 05-09-2022 12-08-57](https://user-images.githubusercontent.com/77765830/188338919-6702da54-77bc-480b-801d-1c40a10c0ab3.png)
Exchangerate
![freeosgov2 - XPR Account - Proton Testnet 05-09-2022 12-09-36](https://user-images.githubusercontent.com/77765830/188338926-c2765871-3a9b-4fb4-965d-0c0d587d6650.png)
