### ISSUE TITLE
Point to FREEOS with FREEOS unable to find key

### ISSUE THREAD

**Issue by stuartmcphersonflipmind** [FreeosDAO/freeosgov_frontend#54]
![image](https://user-images.githubusercontent.com/58194035/188003920-dbf0c4ec-6427-466b-a049-52b5f70d8347.png)

Also receive this Error when Converting FREEBI to FREEOS with FREEOS

**Comment by tommccann777** [comment]
Hi @stuartmcphersonflipmind I notice that the transfer transaction has specified 1 POINT as the fee (in the quantity field). It should be 1.0000 FREEOS

<img width="569" alt="image" src="https://user-images.githubusercontent.com/18106735/188296662-070be6c1-f83d-40e0-afe6-3629e518c066.png">

**Comment by stuartmcphersonflipmind** [comment]
All good this is fixed in v0.2.12 closing
