### ISSUE TITLE
Point to FREEOS with XPR/XUSDC incorrect mint fee

### ISSUE THREAD

**Issue by stuartmcphersonflipmind** [FreeosDAO/freeosgov_frontend#55]
![image](https://user-images.githubusercontent.com/58194035/188006945-2d5df2a1-3d6f-46b2-8459-056f74f5cb11.png)

Also get this error when converting from FREEBI

**Comment by tommccann777** [comment]
Hi @stuartmcphersonflipmind, I have fixed this in v0.9.51 of the contract. It is ready for a re-test.

**Comment by stuartmcphersonflipmind** [comment]
@tommccann777  Its Working now when mint fee is the Minimum value but not when using the Mint fee percentage

**Comment by judytan21** [comment]
28/9/22 Closing this after consulting Stuart.
