### ISSUE TITLE
Unverified, unregistered user unable to access Mint page.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#61]
7/9/22 freeosgov2 frontend v0.2.16 backend v0.9.52
billbeaumont 'e' unverified and unregistered user was unable to access the Mint page to mint FREEOS. 
Expecting Mint menu item to be available/visible to all users as per Tom's **updated Mint FREEOS specs** (see screenshot) below:

**Note:** The previous version requires the menu item for the Mint page to be only available for all registered and verified users (where [userRecord].account_type == "v" or "b" or "c"). This appears to have now changed to include all users.

Tom's Updated specs:
<img width="715" alt="Screen Shot 2022-09-07 at 1 29 58 PM" src="https://user-images.githubusercontent.com/77765830/188769874-e8e98eed-9eab-43b8-b49c-cf3fe366b7f6.png">
Mint menu item unavailable 
![Freeos Governance dApp 07-09-2022 13-48-17](https://user-images.githubusercontent.com/77765830/188770730-7133bd5b-45fd-4b85-9c91-28c34bad906c.png)

**Comment by stuartmcphersonflipmind** [comment]
Updated in v0.2.17

**Comment by judytan21** [comment]
12/9/22 freeosgov2 frontend v0.2.17 backend v0.9.53. Fixed.
Mint menu item now available/visible to unverified, unregistered users.
![Freeos Governance dApp 12-09-2022 15-02-51](https://user-images.githubusercontent.com/77765830/189566624-529beca7-75aa-4c33-a29f-b348a0ca8a00.png)
