### ISSUE TITLE
On Mint FREEOS tab, remove redundant 'n' from label.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#62]
12/9/22 freeosgov2 frontend v0.2.17 backend v0.9.53 
On Mint FREEOS tab, remove chr 'n' from label "n1. Choose a balance to Mint from:".
![Freeos Governance dApp 12-09-2022 12-10-41](https://user-images.githubusercontent.com/77765830/189555316-d917ef15-5799-42f5-802f-4ea331058ed4.png)

**Comment by stuartmcphersonflipmind** [comment]
Fixed in v0.2.18

**Comment by judytan21** [comment]
14/9/22 Retest. freeosgov2 frontend v0.2.18 backend v0.9.55 Fixed.

![Freeos Governance dApp 14-09-2022 11-06-11](https://user-images.githubusercontent.com/77765830/190024618-05afd7e4-674e-40e7-96c2-29f98ee2942a.png)
