### ISSUE TITLE
Was able to select paying mint fee by FREEOS even tho' user do not have sufficient FREEOS. 

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#63]
12/9/22 freeosgov2 frontend v0.2.17 backend v0.9.53
Veronicavale balances: XPR: None, XUSDC: None, CREDITs: None, POINTs: 6500.0000 POINT, Locked POINTs: 4362.5571 POINT, MFF: 1194.4857 POINT, FREEBI: 29.1105 FREEBI, FREEOS: 0.2345 FREEOS
On Mint FREEOS tab, mint 6000 POINTs to FREEOS. Mint fee calculated as 360 FREEOS User's FREEOS bal=0.2345 FREEOS.
The 'Pay the mint fee with" field allowed user to select FREEOS even tho' they do not have enough FREEOS to pay for the mint fee, resulting in an 'overdrawn balance' assertion msg being displayed. Expecting frontend to not allow FREEOS to be selected if user does not have enough FREEOS to pay for mint fee. Currently, it appears that this check is in place for mint fee payment by XPR and XUSDC.
![Freeos Governance dApp 12-09-2022 12-42-57](https://user-images.githubusercontent.com/77765830/189557453-f0d31b0c-0b70-4f52-9983-6104b25ac0ca.png)
![Freeos Governance dApp 12-09-2022 12-43-09](https://user-images.githubusercontent.com/77765830/189557460-8b7b6616-d4df-4446-8900-14dcf412b8a3.png)
<img width="475" alt="Screen Shot 2022-09-12 at 12 28 01 PM" src="https://user-images.githubusercontent.com/77765830/189557503-e0044ad0-4841-47ed-a8f3-ef11557d5c46.png">

**Comment by stuartmcphersonflipmind** [comment]
Fixed in v0.2.21 Button disabled and insufficient funds msg shown

**Comment by judytan21** [comment]
19/9/22 Retest. freeosgov2 frontend v0.2.22 backend v0.9.56. A generic message "You do not have enough to complete the transaction" was displayed instead of the asserting message 'overdrawn balance'. Fixed. 
![Freeos Governance dApp 19-09-2022 12-05-33](https://user-images.githubusercontent.com/77765830/190933939-c2e278b8-fb50-4d4e-b39d-d064cf20672b.png)
