### ISSUE TITLE
Minting POINTs to FREEOS where AirClaim POINTs balance exceeds available POINTs balance.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#64]
12/9/22 @Tom | freeos.io | freedao.io @Stuart Question? When minting AirClaim Points to FREEOS, if the AirClaim POINTs bal exceeds the available POINTs balance, will selecting Max for Amt to Mint show the Available POINTs balance instead?

**Comment by tommccann777** [comment]
v0.9.54 of the freeosgov contract now checks that the user has a sufficient balance of POINTs or FREEBI before going ahead with the transaction. If not then an assert error will be thrown with messages:

"user has insufficient POINTs balance"
OR
"user has insufficient FREEBI balance"
as appropriate.

I have request the frontend devs to make the following changes. See page 10 of the mintfreeos frontend spec here:
https://docs.google.com/document/d/18sPsC1iG2_1Jd5gUK32Nxj4i1HTQV5pZfgz3fvgvjFM/edit#

The relevant sections are (changes in red):
<img width="732" alt="image" src="https://user-images.githubusercontent.com/18106735/189779380-fa295459-6bd7-44dc-b73b-1139e93252ff.png">

and

<img width="735" alt="image" src="https://user-images.githubusercontent.com/18106735/189779623-6798bab7-924d-437d-97fa-0b95f2a42fcb.png">

**Comment by judytan21** [comment]
19/9/22 Please refer to new issue#71 logged. Closing this issue.
