### ISSUE TITLE
Expected XPR/XUSDC balance is incorrectly showing as POINTs instead of XPR/XUSDC.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#65]
12/9/22 freeosgov2 v0.2.17 backend v0.9.53
When minting POINTs to FREEOS, paying mint fee by XPR, the XPR balance was showing as 91.1406 Points. Expecting the XPR balance to be 91.1406 XPR.
Expected Transaction Balances:
Points balance: 2155 Points
XPR balance: 91.1406 Points
FREEOS balance: 53.6183 FREEOS

![Freeos Governance dApp 12-09-2022 17-07-45](https://user-images.githubusercontent.com/77765830/189578038-becdea58-e1d1-4f46-ad8c-58d9fb097647.png)

**Comment by judytan21** [comment]
13/9/22 freeosgov2 v0.2.17 backend v0.9.54 Same issue with minting POINTs to FREEOS and paying mintfee by XUSDC. The XUSDC balance was also showing as XUSDC balance: 9.993506 Points instead of 9.993506 XUSDC.
![Freeos Governance dApp 13-09-2022 11-51-31](https://user-images.githubusercontent.com/77765830/189778232-a3059f44-6968-44a7-9232-275f56422de6.png)

**Comment by sjmcpherson** [comment]
Fixed in 0.2.19

**Comment by judytan21** [comment]
19/9/22 freeosgov2 v0.2.22 backend v0.9.56
1) When minting POINTs to FREEOS, paying mint fee by XPR, the XPR balance is now in XPR. Fixed.
2) When minting POINTs to FREEOS, paying mint fee by XUSDC, the XUSDC balance is now in XUSDC. Fixed.
![Freeos Governance dApp 19-09-2022 11-28-05](https://user-images.githubusercontent.com/77765830/190932837-66a756d4-7aac-40ae-8770-ae4a7f66c988.png)
![Freeos Governance dApp 19-09-2022 11-39-35](https://user-images.githubusercontent.com/77765830/190933206-fb52af3e-de58-4fb5-a72a-aeb10767ea5f.png)
