### ISSUE TITLE
UI Observation: Line 'AirClaim points used' displayed when minting FREEBI to FREEOS.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#67]
13/9/22 freeosgov2 frontend v0.2.27 backend v0.9.54
I've noticed that when minting FREEBI to FREEOS: 
The  line "AirClaim points used: 0 Points" appears to be displayed only when the user (vivvestin) has AirClaim Points. It's not shown if the user (vickvindaloo) does not have any AirClaim Points. 
Is there a reason for this? 
Wouldn't the AirClaim points used always be 0 when minting FREEBI to FREEOS? Hence, do we need to show this line?

Screenshot where calc mint fee of 1.2 FREEOS applies.
![Freeos Governance dApp 13-09-2022 15-01-30](https://user-images.githubusercontent.com/77765830/189809968-e1ea6607-4af0-4017-969c-5f927bf62c46.png)
Screenshot where the min mint fee of 1 FREEOS applies.
![Freeos Governance dApp 13-09-2022 15-26-19](https://user-images.githubusercontent.com/77765830/189809984-5e015f11-616b-4b09-a470-6f3ce8dd33e8.png)

**Comment by stuartmcphersonflipmind** [comment]
Fixed in v0.2.21 AirClaim bal hidden if unused

**Comment by judytan21** [comment]
19/9/22 Retest. freeosgov2 frontend v0.2.22 backend v0.9.56. The line 'AirClaim points used' not displayed in both scenarios when retesting with vivvestin and vickvindaloo accounts. Fixed.
vivvestin (has 99 AirClaim POINTs)
![Freeos Governance dApp 19-09-2022 12-30-33](https://user-images.githubusercontent.com/77765830/190934741-38f770b4-d648-46f6-a3bc-887fafbc7e1a.png)
vickvindaloo (No AirClaim POINTs)
![Freeos Governance dApp 19-09-2022 12-39-25](https://user-images.githubusercontent.com/77765830/190935000-46cf688e-e52f-4112-a3f3-4b432b2249e8.png)
