### ISSUE TITLE
Empty page presented when logging in as unregistered, unverified user.  

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#7]
20/7/22 Governance Frontend v0.1.4
1) Login as alanappleton, unverified (account type 'd'). Not registered (no Participant record).
Was presented with the empty page, screenshot attached. Expecting to be presented with the 'Unverified' page.
Select 'Activities' menu item, same results.
2) Login as billbeaumont, unverified (account type 'e'). Not registered (no Participant record).
Was also presented with the empty page. Expecting to be presented with the 'Unverified' page.
Select 'Activities' menu item, same results.
![Freeos App 20-07-2022 11-55-43](https://user-images.githubusercontent.com/77765830/179867967-69fc07ae-4182-4935-9fe4-3daf226633da.png)

**Comment by sjmcpherson** [comment]
Hi Jude, according to my records alanappleton is registered, see below
![Screen Shot 2022-07-20 at 1 02 49 PM](https://user-images.githubusercontent.com/2390422/179873461-0db7ce36-3ca5-448a-bb00-4352fccc0bbd.png)

Likewise for billbeaumont, from what I believe a User shouldnt get in this state but I will make a change so the "Sorry your Not Verified" message comes up incase

**Comment by judytan21** [comment]
Ooops! my bad. alanappleton and billbeaumont were registered....so used to the previous User table...so looking in User table instead of Participant table. Will retest with another account.

**Comment by judytan21** [comment]
Hi Stuart, currently there are unverified registered user in Governance eg.
alanappleton, billbeaumont cos the backend is not currently stopping
unverified from registering. Spoke to Tom and he said that will be in
tomorrow's release. He's happy for you to show the "Sorry Not verified.."
page for users in this state.

**Comment by judytan21** [comment]
Hi Stuart, currently there are unverified registered user in Governance eg. alanappleton, billbeaumont cos the backend is not currently stopping unverified from registering. Spoke to Tom and he said that will be in tomorrow's release. He's happy for you to show the "Sorry Not verified.." page for users in this state. Thanks.

**Comment by judytan21** [comment]
20/7/22 Retested. freeosgov2 frontend v0.1.4. Accounts: ethanedwards (e) and dannydevito (d). Both unverified and not registered in freeosgov2 (no Participants record). Presented with 'Sorry you are unverified.." page. Fixed
![Freeos App 20-07-2022 14-10-48](https://user-images.githubusercontent.com/77765830/179881690-e4a55f81-e9e2-4f1e-a83d-83494a53bfa3.png)

**Comment by judytan21** [comment]
26/7/22 Retested. freeosgov2 frontend v0.1.6. 
1. Login as unverified user->dannydevito, type=d. Not registered (No participant record).
After login completed. Was returned to Connect wallet page. Expecting to be presented with 'Sorry you are unverified" page.
2. Login as unverified user->powderblue, type=e. Not registered (No participant record).
After login completed. Was returned to Connect wallet page. Expecting to be presented with 'Sorry you are unverified" page.
Was working in previous release v0.1.4.

**Comment by judytan21** [comment]
27/7/22 Retest. freeosgov2 frontend v0.1.7.
1. Login as unverified user->dannydevito, type=d. Not registered (No participant record). Fixed
After login completed. Presented with 'Sorry you are unverified" page.
2. Login as unverified user->powderblue, type=e. Not registered (No participant record).
After login completed. Presented with 'Sorry you are unverified" page. Fixed.
![Freeos App 27-07-2022 15-02-26](https://user-images.githubusercontent.com/77765830/181151604-947a2fe5-6435-4458-8c7a-cc11f4d2e332.png)
![Freeos App 27-07-2022 15-04-40](https://user-images.githubusercontent.com/77765830/181151822-f4b29723-ddd1-4654-a806-73504fc971f5.png)
