### ISSUE TITLE
Mint POINTs to FREEBI should be restricted to verified users only.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#72]
21/9/22 freeogov2 frontend vf0.2.22 backend v0.9.56i 
Currently, when an unverified user, dannydevito type 'd' attempts to mint Points to FREEBI, assertion failure with message: "user is not registered" is displayed.
Minting of POINTs to FREEBI should be restricted to verified users only.
Following discussion with JeromeK this morning, he'd like the "Mint FREEBI" tab to be accessible by unverified users but the "Mint FREEBI" button has to be disabled with a red text "You must be verified to mint FREEBI" displayed above the "Mint FREEBI" button. 
Current behaviour:
![Freeos Governance dApp 21-09-2022 11-18-30](https://user-images.githubusercontent.com/77765830/191381456-92e23acc-b6e9-4c8c-bf7f-38dccb98d9f1.png)

<img width="467" alt="Screen Shot 2022-09-21 at 11 19 03 AM" src="https://user-images.githubusercontent.com/77765830/191381426-4ce26153-7731-4e8f-b9aa-80c6a41d52c1.png">

**Comment by conorseed** [comment]
@judytan21 - I've updated this to use the "Get Verified" component instead of red text to keep it consistent with the rest of the dApp where users are not verified. Happy to change if needed!

![Screen Shot 2022-09-22 at 10 10 57 AM](https://user-images.githubusercontent.com/13262289/191620599-bc053250-ea2d-479c-bcd8-8c4585e076c7.png)

**Comment by judytan21** [comment]
27/9/22 freeogov2 frontend vf0.2.25 backend v0.9.57 dannydevito type 'd' unverified, unregistered was unable to mint FREEBI. Fixed.
![Freeos Governance dApp 27-09-2022 15-03-51](https://user-images.githubusercontent.com/77765830/192414522-99471e6f-42e3-4ba5-9356-d1ede0f4d68a.png)
