### ISSUE TITLE
Unable to proceed to the next page after completing Survey.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#75]
21/9/22 freesogov2 frontend v0.2.22
Logging this issue on behalf of JeromeK.
Unable to proceed to the next page after completing Survey when running dApp in both Safari and Chrome on a Mac. 
Accounts used were: bigvern and vivvestin.
Steps:
1. On 'Welcome to Survey' page, completed Survey and Submit.
2. Presented with the 'Welcome to Survey' page again. On clicking the Submit button again, an assertion failure message that he has already completed the Survey was displayed.
Expecting to be taken to the next page i.e. 'Thanks for participating in this week's survey...Next: The weekly Vote' page.
![Freeos Governance dApp 21-09-2022 12-01-57](https://user-images.githubusercontent.com/77765830/191385493-f0c70d17-6773-445b-b84e-10f41243309c.png)
Unable to proceed to the following page:
![Freeos Governance dApp 21-09-2022 12-03-40](https://user-images.githubusercontent.com/77765830/191385636-c1d0cfaf-b69c-4df9-b448-6ed1fd2e75cc.png)

**Comment by conorseed** [comment]
@judytan21 I've checked this on my end on mac in Brave and Safari with "bigvern" and "vincentvegan" and haven't been able to replicate. Are you able to see if you can replicate the issue on your end?

**Comment by judytan21** [comment]
27/9/22 freeosgov2 frontend v0.2.25 backend v0.9.57. Replicated scenario using verovera. Unable to proceed to next page when completing Survey and Vote. Frontend/backend iteration out of sync. Frontend showing as iteration 462285 and backend 462286.
![image](https://user-images.githubusercontent.com/77765830/192406912-a0b8697d-1dbb-44e9-8113-6879813521d4.png)
![image](https://user-images.githubusercontent.com/77765830/192406981-64c5cd44-a39e-44aa-a46d-210a0ddb9ccb.png)

![image](https://user-images.githubusercontent.com/77765830/192406524-d10e6a6b-b514-4773-8fd0-d3c193b8d233.png)
![image](https://user-images.githubusercontent.com/77765830/192406619-f8319e2e-f066-4591-8282-c8c67c14a47c.png)

**Comment by judytan21** [comment]
27/9/22 Retest. freeosgov2 frontend v0.2.26 backend v0.9.57. Replicated scenario using verovera. Frontend/backend iteration in sync. Frontend showing as iteration 462291 and backend 462291. Was able to complete vote and proceed to the next page.
![Account - Proton Testnet 27-09-2022 15-36-06](https://user-images.githubusercontent.com/77765830/192418516-5a9d2c38-9c06-4e6a-8fbd-f2884119bb61.png)
![Freeos Governance dApp 27-09-2022 15-36-51](https://user-images.githubusercontent.com/77765830/192418537-d2f3035b-3082-4242-a434-2427343d2142.png)
![Freeos Governance dApp 27-09-2022 15-39-33](https://user-images.githubusercontent.com/77765830/192419070-82f9a372-fe8a-44ea-b2b7-471ea5eef28f.png)

**Comment by judytan21** [comment]
28/9/22 freeosgov2 frontend v0.2.26 backend v0.9.57, JeromeK confirms survey and vote is working for him. Fixed.
Tom | freeos.io | freedao.io — 28/9/22 Today at 16:13
JK has reported he sees the correct behaviour after completing a survey.
He says vote works ok too.
