### ISSUE TITLE
On Ratify page, unable to select link for more information.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#77]
On Ratify page, "click here" should be a link to allow user to view more information.

![Freeos Governance dApp 21-09-2022 14-50-56](https://user-images.githubusercontent.com/77765830/191403929-c15bd244-84aa-483d-9aee-5ed8be665557.png)

**Comment by conorseed** [comment]
@judytan21 - haven't updated this text yet. Awaiting Jerome's update, and then will add in the link! 
Will update this once that's done.

**Comment by judytan21** [comment]
27/9/22 Retest. freeosgov2 frontend v0.2.25 backend v0.9.57. Click here link is now selectable and was taken to Ratify section of wiki. Fixed.
![Freeos Governance dApp 27-09-2022 16-52-00](https://user-images.githubusercontent.com/77765830/192428150-81acc909-e745-4afb-b76e-573de77fda0d.png)
