### ISSUE TITLE
Wording change required on 'Welcome to the Vote' page.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#8]
20/7/22 Governance Frontend v0.1.4 Vote Completion.
In the following paragraph, change "take some take the time to understand" to "take some time to understand".
Thanks for being active in stewarding this economy. Besides empowering your own financial freedom, your answers also affect the FREEOS community. The bonus is your participation is rewarded when you ‘Claim’. Initially, it may take some take the time to understand each economic tool - but that will change. For more info refer to:
![Freeos App 20-07-2022 12-29-24](https://user-images.githubusercontent.com/77765830/179870427-2d744d5f-09f3-4d1a-be87-3f0bfb6afd94.png)

**Comment by judytan21** [comment]
26/7/22 Retest. freeosgov2 v0.1.6. Wordings not corrected. Still the same. Not fixed
![Freeos App 26-07-2022 15-29-32](https://user-images.githubusercontent.com/77765830/180917101-ee09ac96-0ea3-4bdb-9416-00b2151efc62.png)
,

**Comment by stuartmcphersonflipmind** [comment]
Wording fixed now v1.12

**Comment by judytan21** [comment]
2/8/22 Retest. freeosgov2 v0.1.13. Wordings corrected. Fixed
<img width="528" alt="Screen Shot 2022-08-02 at 11 38 08 AM" src="https://user-images.githubusercontent.com/77765830/182262694-a9d64344-072b-477f-ae04-594f6e699389.png">
.
