### ISSUE TITLE
Alpha Test - Assert Error minting BEEBI

### ISSUE THREAD

**Issue by conorseed** [FreeosDAO/freeosgov_frontend#82]
User: conalpha

Steps: 
1. Go to Mint -> Mint Freebi
2. Amount to mint: "100"
3. Click "Mint BEEBI"
4. Sign transaction
5. Assert error returned `inline action's code account beebi does not exist`

![Screen Shot 2022-10-06 at 12 13 44 PM](https://user-images.githubusercontent.com/13262289/194180747-104bb50d-61b1-44b0-b644-09c89d169087.png)

transaction data here:
![Screen Shot 2022-10-06 at 12 17 29 PM](https://user-images.githubusercontent.com/13262289/194180828-02df2070-0d06-4feb-87ed-e8544e690337.png)

**Comment by tommccann777** [comment]
Changed parameter for the BEEBI contract. Should fix the issue. Please re-test.

**Comment by conorseed** [comment]
@tommccann777 retested. 

Returns new assert error: 
`assertion failure with message: attempt to subtract asset with different symbol`

![Screen Shot 2022-10-06 at 12 27 24 PM](https://user-images.githubusercontent.com/13262289/194181822-459897a3-c3da-4c6e-a035-fc40fa735ded.png)

**Comment by tommccann777** [comment]
Fix applied. Please re-test

**Comment by conorseed** [comment]
@tommccann777 retested with original steps and seems to be fixed 🙌

@judytan21 - I'll let you confirm and close when you're ready.
