### ISSUE TITLE
Alpha Test-Assertion failure encountered on registration.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#83]
6/12/22 jualpha unverified NFT holder was prompted to register. On registration, encountered assertion error.
![Freeos Governance dApp 06-10-2022 12-10-59](https://user-images.githubusercontent.com/77765830/194181071-d2e2b404-d038-4591-b892-672e0ea0fc03.png)
![Freeos Governance dApp 06-10-2022 12-18-12](https://user-images.githubusercontent.com/77765830/194181078-2cc94bd7-b7e0-433e-90a6-aca34f96a058.png)

**Comment by tommccann777** [comment]
Problem fixed. Please re-test

**Comment by judytan21** [comment]
6/10/22 Retest. Registration successful. Fixed.
