### ISSUE TITLE
Alpha Test - Assert Error: Cannot send BEEBI to verified user "jualpha"

### ISSUE THREAD

**Issue by conorseed** [FreeosDAO/freeosgov_frontend#85]
user: conalpha

What happened: 
I tried sending BEEBI to all verified users. All were successful except for to user "jualpha", who should be verified. 

Steps:
1. Go to Transfer -> Send BEEBI
2. to account: "jualpha"
3. transfer amount: 1
4. Press Send and sign transaction
5. Returns assert error 
`assertion failure with message: the recipent must be a verified Freeos user`

![Screen Shot 2022-10-06 at 12 57 36 PM](https://user-images.githubusercontent.com/13262289/194184665-6cceb0bd-3dc2-47be-95f4-171acc6932c0.png)

**Comment by conorseed** [comment]
Retested: successful transfer to "jualpha".

**Comment by judytan21** [comment]
6/10/22 Tom has changed rule to allow all registered users to receive/transfer FREEBI. Unverified, hasNFT user i.e. jualpha can receive/transfer FREEBI after registering. However, unverified, unregistered user i.e. stualpha will not be able to receive/transfer FREEBI.
