### ISSUE TITLE
Alpha Test: Assertion error encountered when Claiming.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#87]
6/10/12 jualpha Voted and Ratified in Iter 1. Next iter 2, when claiming, assertion failure with message: tokens can only be issued to issuer account
![Freeos Governance dApp 06-10-2022 13-13-44](https://user-images.githubusercontent.com/77765830/194186283-82212ff5-02af-429a-abf0-f97b06f537de.png)

**Comment by tommccann777** [comment]
Issue Fixed. Users successfully claiming now. Please re-test

**Comment by judytan21** [comment]
6/10/12. Retest. Claim successful. Fixed.
