### ISSUE TITLE
Beta Test: When minting BEEBI to BETA, BEEBI balance was unavailable for selection prior to refreshing.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#94]
26/10/22 Governance Beta Testing: Frontend v0.3.8-beta. Account: Tom's Account.
Steps
1. BEEBI balance was 0. 
2. Mint POINTs to BEEBI. 
3. Proceed to Mint BEEBI to BETA.
4. Drop down list: BEEBI was unavailable for selection.
5. Refresh.
6. BEEBI was now available for selection.
7. Mint BETA successful.

**Comment by judytan21** [comment]
26/10/22 Tested this using my account and was able to mint BEEBI to Beta with having to do a refresh. Took a sec or two for the BEEBI balance to be updated after minting but it worked fine for me.

**Comment by judytan21** [comment]
26/10/22 Frontend v0.3.8-beta.
Tom and I retested this using his Account and was able to replicate the issue. Hence, it works for me but not for Tom.

**Comment by stuartmcphersonflipmind** [comment]
Note for me, Dropdown Options are enabled/disabled on Initialization this needs to be dynamic

**Comment by judytan21** [comment]
31/10/22. Frontend v0.3.9-beta. Retest. Able to replicate issue using tommccann account. 
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/77765830/198918265-c4b7e261-6be6-4eca-9665-75f83f14eb21.png">

**Comment by stuartmcphersonflipmind** [comment]
Options are dynamic and will change with refresh now in v0.5.0

**Comment by tommccann777** [comment]
Ready for re-test

**Comment by judytan21** [comment]
21/11/22 Frontend v0.5.7-beta. Retest above scenario and was able to mint BEEBI to BETA without having to refresh. Fixed.
<img width="503" alt="Screen Shot 2022-11-21 at 3 02 50 PM" src="https://user-images.githubusercontent.com/77765830/202945476-469db36f-78f7-4090-903f-810fcfdb5d6f.png">
