### ISSUE TITLE
Beta Test: On Survey page. Click here link does not work.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#95]
26/10/22 On Survey page, "click here" was not working. 
Was able to replicate Bolelang's issue.
On Welcome to Survey page, click here...encountered error "This site cannot be reached"
Appears to be a problem for all Click here links and Info link too. Looks like the wiki is unavailable.
<img width="673" alt="Screen Shot 2022-10-26 at 12 25 08 PM" src="https://user-images.githubusercontent.com/77765830/197900423-ffc2f733-2c96-465e-a72c-92d295af7c63.png">

**Comment by tommccann777** [comment]
Fixed
