### ISSUE TITLE
Beta Test: Community tester was able to submit Survey 3 times and was not taken to the next page.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#96]
26/10/22 Bolelang from the community was able to submit Survey 3 times and was not taken to the next page. See screenshot below. Asked him to logout, refresh and login again, checking that he was running on the latest frontend v0.3.8-beta. 
He retested and reported it was still the same.
Survey worked fine for me, hence unable to replicate issue.
<img width="735" alt="Screen Shot 2022-10-26 at 2 18 30 PM" src="https://user-images.githubusercontent.com/77765830/197912197-e70bb958-1a4b-4159-9df9-78c7ebd352c8.png">

**Comment by stuartmcphersonflipmind** [comment]
Has anyone got this issue recently? maybe its been resolved

**Comment by judytan21** [comment]
21/11/22 Discord JeromeHartigan to find out if anyone is still experiencing this issue.
Jude — Today at 10:42
Hi @jeromehartigan,  Issue#96 - Community tester was able to submit Survey 3 times and was not taken to the next page. @Stuart would like to know if anyone got this issue recently?

**Comment by judytan21** [comment]
22/11/22 JH advised issue can be closed. 
jeromehartigan — 22/11/22 Today at 11:54
@Jude Bolelang has no objection to closing that ticket. 🙂
