### ISSUE TITLE
Beta Test-Assert message encountered when minting BEEBI to BETA paying mint fee with BETA.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#98]
1/11/22 Logging issue on behalf of Dan Kimball where an assert message was displayed when minting BEEBI to BETA paying mint fee with BETA.
Dan Kimball — Today at 08:22
I tried to mint 100 BETA paying fee with BEEBI but was unable to complete got this message...
![image](https://user-images.githubusercontent.com/77765830/199114896-e69990c6-871d-447b-bc70-60a78edcc2be.png)
![image](https://user-images.githubusercontent.com/77765830/199114979-e30ac223-1bc4-4e3c-a0a9-f509678c48d4.png)

**Comment by judytan21** [comment]
1/11/22 Tom has sorted the issue. Awaiting Dan to retest and confirm if it's fixed. Will keep issue open for now.
Tom | freeos.io | freedao.io — Today at 14:54
Yes, I cleared the erroneous credit record
Jude — Today at 14:54
Did he retest?
Tom | freeos.io | freedao.io — Today at 14:54
I've asked Dan (via Discord) to try it again

**Comment by judytan21** [comment]
2/11/22 Dan Kimball retested. Working now. Fixed.
Dan Kimball — Today at 11:31
@Jude  @Tom | freeos.io | freedao.io  @jeromehartigan   Tested the second combination as you requested... Minted 100 BETA from BEEBI Paid fee in BETA.  Got the WHoo HOO and the balanced changed as expected... Looks like it works now!
![image](https://user-images.githubusercontent.com/77765830/199355180-a2074334-1657-47f2-be75-23c79f4f09b2.png)
![image](https://user-images.githubusercontent.com/77765830/199355214-c3c52382-d4d1-4e36-b190-aa4d5fa626d5.png)
Jude — Today at 11:35
Yay! Great job @Dan Kimball Thank you so much. Are you happy for me to close the issue?

**Comment by tommccann777** [comment]
Addresses in code. Not reproducible
