### ISSUE TITLE
Beta Test-Issue when minting max AirClaim Allowance.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#99]
1/11/22 Logging issue on behalf of JeromeH.
jeromehartigan — Yesterday at 19:05
I mint max but it only allows 900 of 4.5k AirClaim Allowance is this right? Why?
![image](https://user-images.githubusercontent.com/77765830/199116274-b4150789-a765-463b-ba17-e59b368bb568.png)

**Comment by judytan21** [comment]
1/11/22 Unable to replicate JH's issue. Minted max AirClaim POINTs of 10990 POINTs successfully for tommccann.

**Comment by judytan21** [comment]
1/11/22 Frontend v0.4.1=beta. JeromeH retested and it worked. Issue closed.
Tom | freeos.io | freedao.io — Today at 11:43
Maybe we put it down as a blip that was solved in the latest release? It's hard to understand why it works for us but not JH in particular
It might be worth asking JH if you can see him reproduce it
jeromehartigan — Today at 11:45
I'll try now 🙂
Jude — Today at 11:45
Maybe @jeromehartigan can get the community to try minting max AirClaim POINTs to see if anyone else can reproduce it.
Tom | freeos.io | freedao.io — Today at 11:46
You should get 3596.0449 POINT when you hit Max (I just checked your mintfee-free allowance) 
jeromehartigan — Today at 11:46
Yes that's what I get now -
Tom | freeos.io | freedao.io — Today at 11:47
Thank gawd for that
Sorry. Gawd should be capitalised 🙂
jeromehartigan — Today at 11:48
Gawd is GOOOOOOOOOOOOOOOOOOOOOOOOOOOOD!!!
Tom | freeos.io | freedao.io — Today at 11:48
Yes, never mind capitals, I think the G should take up an entire page!
Jude — Today at 11:48
Awesome! @jeromehartigan are you happy for me to close the issue?
jeromehartigan — Today at 11:48
Yes

**Comment by judytan21** [comment]
2/11/22 Frontend v0.4.1-Beta. Account: emilyplay unverified user. Was able to replicate JH's issue. Reopen issue.
Jude — Today at 12:00
@Tom | freeos.io | freedao.io @jeromehartigan @Stuart I was able to replicate JH's issue.  When minting BETA from AirClaim Allowance, clicking MAX button, the Amount to Mint box was showing only 490 POINTs when the AirClaim Allowance Bal=990 POINTs. Looks like it's displaying  available POINT balance instead of the AirClaim Allowance Balance. Will reopen issue#99. 
When I try to overwrite the amount by entering 990 POINTs in the Amount to Mint box, an error message: "You do not have enough to complete the transaction" was displayed.
![image](https://user-images.githubusercontent.com/77765830/199358961-0088f218-5310-4751-aefd-d011e95ae8e4.png)
![image](https://user-images.githubusercontent.com/77765830/199359020-8bf100e1-dfbd-4ab2-9d5c-db84224231f1.png)
![image](https://user-images.githubusercontent.com/77765830/199368981-0be3c094-db91-42ce-9364-0dea8ce199e4.png)

**Comment by judytan21** [comment]
@stuartmcphersonflipmind 
2/11/22 Hi Stuart, please do not fix this issue yet till Tom has sought JK's opinion. Ta!
Tom | freeos.io | freedao.io — Today at 13:34
@Jude Can you inform @Stuart  please - just to be aware. Not to fix...yet. We'll get @Jerome | freeos.io | freedao.io's opinion first.

**Comment by tommccann777** [comment]
Behaving as expected
